In [10]:
%load_ext autoreload
%autoreload 2

from src.QIRO_Optimizer import *
import os

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


This notebook performs tests with QIRO with the numbers of nodes specified in available_nodes. Seed defines the random seed for the optimization of the quantum algorithms. Demands can be adjusted to define different demands for the CVRP. run_name specifies the name under which the output should be saved. The methods from QIRO_Optimizer are used to perform QIRO.

In [8]:
available_nodes = [4, 5, 6]
np.random.seed(100)
seed = np.random.random_integers(low=10000, size=20)
np.random.seed(100)
demands = np.random.randint(1, 6, max(available_nodes))
demands[0] = 0
run_name = 'tsp_simulated_annealing'

C:\Users\SchnausManue\AppData\Local\Temp\ipykernel_22736\3646151938.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 10000 + 1) instead
  seed = np.random.random_integers(low=10000, size=20)


In [9]:
for n in available_nodes:
    perform_qiro_tsp(n, seed, exp_type='sa', logging=True, run_name=run_name, reps=2, samples=1000)

Starting test run with 4 nodes and seed 5641
Optimization took 0.2170567512512207 seconds
Calculating correlations took 0.03154730796813965 seconds
Simulated Annealing in the first step found solution [0. 2. 3. 1.] with distance 177.0
Total QAOA process took 0.25060272216796875 seconds
Maximum expectation value location: 5
Fixed node 3 at step 2 with correlation 0.228 . Energy is -1023.0 . Best energy is -1023.0
[ 0. -1.  3. -1.]
Optimization took 0.09608173370361328 seconds
Calculating correlations took 0.016003847122192383 seconds
Total QAOA process took 0.11208558082580566 seconds
Maximum expectation value location: 3
Fixed node 2 at step 3 with correlation -0.01 . Energy is -623.0 . Best energy is -623.0
[ 0. -1.  3.  2.]
Fixed last node node 1
[0. 1. 3. 2.]
Optimization took 0.1979832649230957 seconds
Calculating correlations took 0.02981710433959961 seconds
Simulated Annealing in the first step found solution [0. 1. 3. 2.] with distance 153.0
Total QAOA process took 0.22780036926